### PR TITLE
Make all dependencies be compatible with RxSwift 4.0

### PR DESCRIPTION
**Pull request by RafaelPlantard**
Support for iOS 8.0 and higher

### CODE REVIEW

**Comment by bobgodwinx** [comment]
@RafaelPlantard I really like your courage 😂  but my question is why on earth do we want to support iOS 8.0 ? take a look at this data here and let me know what you think [market share](https://data.apteligent.com/ios/)

**Comment by RafaelPlantard** [comment]
I just used the "same" OS requirements found at `RxSwift` and `RxCocoa`, what do you think?
Actually I just need support for iOS 9.0
But RxSwift and RxCocoa support also iOS 8.0

**Comment by bobgodwinx** [comment]
@RafaelPlantard let's do support from `iOS 9.0`. can please go through the `@available(iOS 9.3, macOS 10.11, *)` and make sure it's not causing breaking changes?

**Comment by RafaelPlantard** [comment]
Ok!

**Comment by RafaelPlantard** [comment]
@bobgodwinx I closed this PR to open other directly to `ios-9.0` branch.

**Pull request closed without merging**
