### PR TITLE
Add @available attribute to enclosing property

### PR DESCRIPTION
**Pull request by newoo**
Because of build failed #40 , I add @available attribute to enclosing property at showsBackgroundLocationIndicator

### CODE REVIEW

**Comment by bobgodwinx** [comment]
Try bumping the deployment target to iOS 11 and if all the unit tests passes we can release it thanks

**Comment by igor-makarov** [comment]
Hi @bobgodwinx @newoo - what's the status on this, and can I help out?

**Comment by bobgodwinx** [comment]
@igor-makarov Thanks for reaching out maybe you could check the deployment target and bump it to iOS 11 try running it locally to see if all works.

**Comment by igor-makarov** [comment]
I've checked and it does work! 👍🏻

**Comment by bobgodwinx** [comment]
I think it's Swift problem.. try adding `return` in the front of the context like this 👇🏾 on this PR so we can see what it says. 

```swift
        itBehavesLike(HasEventsBehavior<Bool>.self) {
            return HasEventsBehaviorContext(scheduler, sut.rx.showsBackgroundLocationIndicator)
        }
```

**Comment by igor-makarov** [comment]
@bobgodwinx I cannot edit this PR as I didn't open it...

**Comment by newoo** [comment]
Thanks to @bobgodwinx @igor-makarov

**Comment by newoo** [comment]
I did bump version of deployment target to iOS 11.
This is my first pull request to open source project, so maybe I made a mistake.

If my commits are wrong, please mention me.

**Comment by ferologics** [comment]
Can we merge this in?

**Comment by bobgodwinx** [comment]
Nice people thanks for the contribution 👍🏾

**Comment by igor-makarov** [comment]
@bobgodwinx any chance to make a release?

**Pull request merged**
