### PR TITLE
Update to Swift 4.2

### PR DESCRIPTION
**Pull request by juliancadi**
Adapted to RxSwift/RxCocoa 4.3.0 release supporting Swift 4.2, iOS 12 and Xcode 10.

### CODE REVIEW

**Comment by bobgodwinx** [comment]
👏🏽👏🏽👏🏽

**Comment by juliancadi** [comment]
Thanks for merging @bobgodwinx 👍 I see you are usually the one releasing new versions for this library. Any plan/date for official 1.3.1 release with this update? Do you need some help with that?

**Comment by bobgodwinx** [comment]
@juliancadi Sure... The `Circle CI` is failing at the moment because it's still version `1.0` If you're familiar with the config file. please kindly move it to version 2.0 and it should pass. I'll slice a pod version over the weekend 👍🏾

**Comment by juliancadi** [comment]
I reestablished 'develop' branch that was totally outdated in order to avoid pushing directly to the master. 

`CircleCI` isn't actually failing, it did fail only once when I brought 'develop' back to live, but it should be working just fine now even though it is running on deprecated `CircleCI` 1.0. I'll take a look on the `CircleCI` 2.0 migration tho. I'm not quite familiar with the current `CircleCI` configuration for this project but maybe we can still make it.

**Pull request merged**
