### PR TITLE
chore: change deployment target to iOS 11

### PR DESCRIPTION
**Pull request by nitikorndev**
to solve the issue: https://github.com/RxSwiftCommunity/RxCoreLocation/issues/47

### CODE REVIEW

**Comment by DavidFerreria** [comment]
Waiting for approbation ...

**Comment by santieduardo** [comment]
Waiting

**Comment by santieduardo** [comment]
@bobgodwinx could you check this PR, please? :)

**Comment by av0c0der** [comment]
It is not how the issue should be fixed. Some apps still support iOS 9/10. #47 could be fixed just by limiting the property to iOS 11.

**Comment by ttrznadel** [comment]
Can someone commit this pull request?

**Comment by grangej** [comment]
This is completely broken without this change, its now Sept and Xcode 13 will be released any day.

**Comment by Beniryu** [comment]
Hello,
I'm having the same problem as the others.
Are you going to merge this PR or do I have to recode my entire app in production and / or revert my whole environment?

**Comment by Beniryu** [comment]
@newoo 
@bobgodwinx 
Hey guys, sorry I'm pinging those who seem to be the one doing the merges.
Can you take care of it please? This is a critical issue.

**Comment by santieduardo** [comment]
@Beniryu 
I really gave up waiting for them!
Use this in your podfile: 
```pod 'RxCoreLocation', :git => 'https://github.com/nitikorndev/RxCoreLocation.git', :branch => 'nitikorndev-patch-1'```

Basically it is using the @nitikorndev's pull request for this moment.

**Review by bobgodwinx — APPROVED** [review]

**Comment by bobgodwinx** [comment]
> It is not how the issue should be fixed. Some apps still support iOS 9/10. #47 could be fixed just by limiting the property to iOS 11.

Deprecating iOS 9/10 support. It's been fun but want to focus on mainly the last 3 versions which will be  12, 13, 14 in the near future.

**Comment by bobgodwinx** [comment]
Will create a new pod once `Xcode 13` has a GM

**Comment by thenodelab** [comment]
> @Beniryu I really gave up waiting for them! Use this in your podfile: `pod 'RxCoreLocation', :git => 'https://github.com/nitikorndev/RxCoreLocation.git', :branch => 'nitikorndev-patch-1'`
> 
> Basically it is using the @nitikorndev's pull request for this moment.

Thanks @santieduardo , I did so and it worked

@bobgodwinx Thanks, I'll update to the latest version then

**Comment by Beniryu** [comment]
> @Beniryu I really gave up waiting for them! Use this in your podfile: `pod 'RxCoreLocation', :git => 'https://github.com/nitikorndev/RxCoreLocation.git', :branch => 'nitikorndev-patch-1'`
> 
> Basically it is using the @nitikorndev's pull request for this moment.

Thanks @santieduardo , I did so and it worked

@bobgodwinx Thanks, I'll update to the latest version then

**Comment by santieduardo** [comment]
@bobgodwinx Did not you create the new release and tag?

**Pull request merged**
