### PR TITLE
Use #keypath and unwrap for location manager events

### PR DESCRIPTION
**Pull request by nyekimov**
#keyPath is much better for type safety and dynamic binding. And unwrapping values rather than emitting a default value is more logical.

### CODE REVIEW

**Comment by bobgodwinx** [comment]
@nyekimov This looks really good, I was wondering if you could cleanup the `KeyPaths`  by putting it into extensions like we did for [`Selectors`](https://github.com/nyekimov/RxCoreLocation/blob/fde2c2367c7ca7d6abe849e5dec62444bdf0f05a/Sources/RxSelectors.swift#L11) so you can just extend `KeyPaths` and have the same kind of style as for the selectors. Thanks 👍

**Comment by nyekimov** [comment]
@bobgodwinx sure, will update my PR soon.

**Comment by nyekimov** [comment]
@bobgodwinx updated the PR.

**Comment by bobgodwinx** [comment]
Thanks @nyekimov looks good

**Pull request merged**
