### PR TITLE
Make all dependencies be compatible with RxSwift 4.0

### PR DESCRIPTION
**Pull request by RafaelPlantard**
Support for iOS 9.0 and higher

### CODE REVIEW

**Comment by RafaelPlantard** [comment]
Continue #10

**Comment by bobgodwinx** [comment]
@RafaelPlantard Thanks 👍

**Comment by RafaelPlantard** [comment]
@bobgodwinx can you generate a new release with it?

**Comment by bobgodwinx** [comment]
done https://github.com/RxSwiftCommunity/RxCoreLocation/releases/tag/1.2.0

**Comment by RafaelPlantard** [comment]
Thanks @bobgodwinx

**Pull request merged**
